In [45]:
import numpy as np

a1 = np.random.randint(1,20,size=(3, 4))

In [46]:
a1

array([[15, 18, 18, 19],
       [15, 14,  7, 12],
       [ 6,  8, 10,  1]], dtype=int32)

## create Array

In [9]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [20]:
# linear space between each element in array
# np.linspace(start,end,total_Elements)

arr = np.linspace(1,10,5, dtype="int")
arr

array([ 1,  3,  5,  7, 10])

In [19]:
# np.zeros((rows, cols))
arr = np.zeros((2,5))
print(arr)

arr = np.zeros(10)
arr

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# np.ones((rows, cols))
arr = np.ones((2,5))
print(arr)

arr = np.ones(10)
arr

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# np.full((rows, cols), field values)
arr = np.full((2,3),5,order="F")
arr

array([[5, 5, 5],
       [5, 5, 5]])

In [33]:
# np.eye(rows, cols, key=how much '1' value need to be shifted right)
arr = np.eye(4,k=1)
arr

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## Attribute of Array

In [47]:
arr = a1

In [48]:
# dimention of array
arr.shape

(3, 4)

In [49]:
# total no elements
arr.size

12

In [50]:
# get dimention of array
arr.ndim

2

In [51]:
# get data type of array
arr.dtype

dtype('int32')

## Indexing & Slicing

In [53]:
arr[1]

array([15, 14,  7, 12], dtype=int32)

In [54]:
arr[1, 1:3]

array([14,  7], dtype=int32)

In [60]:
# boolean indexing 
bi = arr%2==0
print(bi)
bi = arr[bi]
bi

[[False  True  True False]
 [False  True False  True]
 [ True  True  True False]]


array([18, 18, 14, 12,  6,  8, 10], dtype=int32)

In [62]:
# Fancy indexing
fi = arr[[2,1],[2,1]]
fi

array([10, 14], dtype=int32)

## Reshaping

In [66]:
arr = a1.reshape(6,2)
arr

array([[15, 18],
       [18, 19],
       [15, 14],
       [ 7, 12],
       [ 6,  8],
       [10,  1]], dtype=int32)

In [67]:
# create vactore 1-D array, it's more memory-efficient.
# make View not copy means change maid a2 effects a1 

a2 = a1.ravel()
a2

array([15, 18, 18, 19, 15, 14,  7, 12,  6,  8, 10,  1], dtype=int32)

In [68]:
#  create vactore 1-D array, Slightly slower
# make Copy not view 

arr = a1.flatten()
arr

array([15, 18, 18, 19, 15, 14,  7, 12,  6,  8, 10,  1], dtype=int32)

In [73]:
# convert row into col and col into row
arr = a1.transpose()
arr

array([[15, 15,  6],
       [18, 14,  8],
       [18,  7, 10],
       [19, 12,  1]], dtype=int32)

In [79]:
np.swapaxes(arr,1, 0)

array([[15, 18, 18, 19],
       [15, 14,  7, 12],
       [ 6,  8, 10,  1]], dtype=int32)

## stack and spliting

In [82]:
#join or merge arrays,  using axis,  default axis=0
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.stack((a, b),axis=1)
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
d = np.array([40, 50, 60])
c = np.vstack((a, b, d))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [40, 50, 60]])

In [88]:
# makes vactor 1d array
c = np.hstack((a, b, d))
c

array([ 1,  2,  3,  4,  5,  6, 40, 50, 60])