In [5]:
import numpy as np

## array creation

In [6]:
arr = np.array([10,20,30,40])
arr

li = [10,20,30,40]
li

[10, 20, 30, 40]

In [7]:
li = [10,20,"abx"]
arr = np.array(li)
arr

array(['10', '20', 'abx'], dtype='<U21')

In [8]:
li = [10,20,3.5]
arr = np.array(li)
arr

array([10. , 20. ,  3.5])

In [9]:
# 2D array
arr = np.array([[10,20,30],[100,200,300],[1000,2000,3000]])
arr

array([[  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [10]:
# generate array by range
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
# create array by filled value is Zero
arr = np.zeros(10)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [14]:
#((row, column))
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# create array by given interval and gives same space between all element of array
# linspace(start, end, totalElements)
arr = np.linspace(1,25,20)
arr

array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
        7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
       13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
       19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ])

## Random number generation 

In [16]:
np.random.rand(5)

array([0.89256389, 0.40410087, 0.6635689 , 0.5952974 , 0.57565341])

In [17]:
np.random.randn(10)

array([-0.98418932, -1.40936354,  0.37938345,  0.665739  ,  0.30185529,
       -0.01191028,  0.56221567,  0.53758419, -0.10759315,  1.74683847])

In [18]:
np.random.randint(10,20,10)

array([19, 12, 19, 10, 16, 11, 17, 10, 13, 17], dtype=int32)

## array Attributes

In [19]:
arr = np.array([[1,2],[10,5],[7,8]])
arr

array([[ 1,  2],
       [10,  5],
       [ 7,  8]])

In [20]:
arr.shape

(3, 2)

In [21]:
arr.size

6

In [22]:
arr.dtype

dtype('int64')

## array methods

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(10)

In [25]:
arr.sum()

np.int64(33)

In [38]:
np.sum(arr,axis = 0)

array([34, 38, 42, 46, 50])

In [39]:
np.sum(arr,axis = 1)

array([15, 40, 65, 90])

In [42]:
arr.mean()

np.float64(10.5)

In [29]:
arr.std()

np.float64(3.2015621187164243)

In [30]:
arr.argmax()

np.int64(2)

In [31]:
arr.argmin()

np.int64(0)

## Reshap array

In [32]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
arr = arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])