In [21]:
import numpy as np

## indexing slicing in Vector

In [10]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[9]

np.int64(9)

In [12]:
arr[4:8]

array([4, 5, 6, 7])

## indexing slicing in metrix

In [14]:
arr = np.arange(10,30).reshape(4,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
arr[1,1]

np.int64(16)

In [16]:
arr[1:3,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

## boolean indexing

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
boolean_index = arr % 2 == 0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr = arr[boolean_index]
arr

array([ 2,  4,  6,  8, 10])