In [1]:
import numpy as np

In [7]:
a1 = np.arange(1,11)
a2 = np.arange(11,21)
print(a1,"\n",a2)

[ 1  2  3  4  5  6  7  8  9 10] 
 [11 12 13 14 15 16 17 18 19 20]


In [4]:
a1 + a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [8]:
a1 -a2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [10]:
a2 + 10

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

## deep copy shallow copy

In [15]:
a3 = a1
print(a3.base)

None


In [28]:
a3[1] =100
a3

array([ 41, 100,  43,  44,  45,  46,  47,  48,  49,  50])

In [29]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a3 = a1.copy()
print(a3.base)

None


In [31]:
a3[1] = 1000
a3

array([   1, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [32]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
a5 = a1.view()
print(a5.base)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
a5[1] =1000
a5

array([   1, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [35]:
a1

array([   1, 1000,    3,    4,    5,    6,    7,    8,    9,   10])